import * as ai from "@/lib/aiWorkspace/queries";
import { readJson } from "@/lib/aiWorkspaceRuntime/http";
import { replyResponse } from "@/lib/aiWorkspaceRuntime/reply";
import { routeRequest } from "@/lib/aiWorkspaceRuntime/routing";
import { aiWorkspace } from "@/lib/env";
import { ApiError } from "@/lib/http";

type Params = { params: { id: string } };

/**
 * Sends a message and streams the reply as NDJSON.
 *
 * `modelId` is the conversational model the admin chose. The router answers an
 * explicit request for a picture with the image model instead, when one is
 * configured, and anything unknown with the default model.
 *
 * `clientId` is generated by the browser once per message. Sending the same one
 * again returns the rows already written and does not ask a model a second
 * time, so a retried request cannot charge twice.
 */
export async function POST(request: Request, { params }: Params) {
  return replyResponse(request, async (admin, tools) => {
    const b = await readJson(request);
    const route = routeRequest({
      content: typeof b.content === "string" ? b.content : "", selectedModelId: b.modelId, catalogue: tools.catalogue,
      hasAttachments: Array.isArray(b.fileIds) && b.fileIds.length > 0,
    });
    if (!route) throw new ApiError("Conversation not found", 404);
    await tools.use(route.option);
    const started = await ai.startReply(admin.id, {
      conversationId: params.id,
      clientId: b.clientId,
      content: b.content,
      fileIds: b.fileIds,
      provider: route.option.provider,
      model: route.option.model,
      maxOutputTokens: aiWorkspace.maxOutputTokens,
    });
    if (!started.created || !started.assistantMessage) {
      return { existing: { existing: true, userMessage: started.userMessage, assistantMessage: started.assistantMessage } };
    }
    const conversation = await ai.getConversation(admin.id, params.id);
    if (!conversation) throw new ApiError("Conversation not found", 404);
    return {
      conversation,
      userMessage: started.userMessage,
      assistant: started.assistantMessage,
      mode: { kind: "reply", userMessageId: started.userMessage.id },
      option: route.option,
    };
  });
}

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
